= Dominic - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets/
:stylesheet: gh-dominic-pages.css
:sectnums:

== Project: 'Budgeteer' - A Desktop Financial Manager to track expenses and incomes so as to better understand savings and earnings for financial freedom

== Overview

=== Project & Product Information

'Budgeteer' is a desktop financial planner application my team of 4 created for our Software Engineering Principles module.
Our main project was to morph an existing code into any other software we opted to. We were evaluated based on our ability to work with existing base code and the quality of our new modifications to
the existing code.

Budgeteer has a command-line interface (CLI) and graphical user interface created using JavaFX. It is for users who enjoy typing to manage their finances responsibly using a desktop interface.
The application revolves around usage of the CLI to manage one's finances. Users can store an `entry` consisting of
`name`, `cashflow`, `date` and `tags` of any form of financial activity in the application.

== Summary of Contributions

*_Major enhancements_* : Morphed the AddressBook4 to Budgeteer.

** `Reason for enhancement`: To enable Budgeteer to keep track of the financial income and expenses of the person.
** `Highlights`: Time taken to read all 10 kLoc to understand and modify the code.
** `My contributions`: Re-factored functions together with variables across classes to make the components compatible and consistent for the application.
Managed to restructure some parts to make it more cohesive.

*_Major Enhancement_*: ability to filter relevant financial data

** *Function*: To provide additional options for user to search for other data entries.
** *Highlights*: Improves the product significantly for users who may not be remember all the data. With this filter,
they can sniff our relevant financial information that matter to them and
save time by not looking all the data one by one.

** *Justification*: To create an effective and efficient way for user to access data that are important and relevant to them conveniently, and to
make sense of what they are spending and when and how much so as to properly make better financial decisions.

*_Major Enhancement_*: added display of relevant sorted data

** *Function*: allows users to sort their data by a specific type and in a specific order
** *Highlights*: This feature improves the product by providing users with different means of manipulating
and reorganising their data. This was a simple but much needed functionality.

** *Justification*: To create an effective and efficient way for user to access data that are important and relevant to them conveniently, and to
make sense of what they are spending and when and how much so as to properly make better financial decisions.

*_Minor Enhancement_#1*: ability to give suggestions in commandBox

** *Function*: display a popup-box of suggested words to autocomplete with when user inputs parts of a word.
** *Highlights*: Improves the product significantly for users who may not be familiar with the software commands and can
save time by keying in parts of a command word and simply complete the command using the list of suggested words.

** *Justification*: To create an effective autocomplete by words instead of entire text, I needed to accurately read
the the entire user input and provide a variable range of suggestions. While it may seem a simple feature, I wrote an extensive amount of code for this feature to ensure the auto complete
performed its role successfully for most of the functions in our software.


*_Minor Enhancement #2_*: ability to prevent tampering of data by locking it
** *Function*: it secures the application via passwords and data encryption
** *Highlights*: The implementation of a password not only provided a layer of security but a means to prove the identity of the user.
It locks and encrypts the password that is cannot be viewed. he implementation of a password requires an extensive analysis of design alternatives.
** *Justification*: Financial data is important as it reveals spending and earning pattern that can be sold to marketers. Needs to be protected.
=

=== *Other Contributions*

** [https://nuscs2113-ay1819s2.github.io/dashboard-beta/#search=&sort=displayName&since=2019-02-10&until=2019-04-12&timeframe=day&reverse=false&repoSort=true]

* *_Project management_* :
** Raised milestones and organized the group to complete each milestones before deadline.
** Ensured that milestone objectives were met and submitted to relevant PRs to module repo
** Support for issues tracker and PRs
** Managed releases for milestones

* *_Documentation_* :
** Did cosmetic tweaks to existing contents of the User Guide and Developer Guide.
** Proof-read, organised documentation to maintain its coherence.

* *_Testing_*:
** Wrote extensive tests to increase coverage of the project

* *_Tools_* :
** Integrated a third party library to the project and the team repo

* *_Debugging team members code_* :
** Provided ideas for possible implementation for other team member's features

* *_Team Management_* :
** Coordinated some team meetings
** Ensured that team members meet feature deadlines set within the team

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the <<../UserGuide, User Guide>>. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=lock]

include::../UserGuide.adoc[tag=filter]

include::../UserGuide.adoc[tag=display]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=CommandsUISupport]

include::../DeveloperGuide.adoc[tag=lock]

include::../DeveloperGuide.adoc[tag=filter]

include::../DeveloperGuide.adoc[tag=display]

