= Jacob Han - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets/
:stylesheet: gh-jacobhan-pages.css


== Project: 'Budgeteer' - A Desktop Financial Manager to track expenses and incomes so as to better understand savings and earnings for financial freedom

== Overview

=== Project & Product Information

'Budgeteer' is a desktop financial planner application my team of 4 created for our Software Engineering Principles module.
Our main project was to morph an existing code into any other software we opted to.

Budgeteer has a command-line interface (CLI) and graphical user interface created using JavaFX. It is for users who enjoy typing to manage their finances responsibly using a desktop interface.
The application revolves around usage of the CLI to manage one's finances.

== Summary of Contributions

*_Major enhancements_* : Feature to return purchasing power and price of an entered stock

** `Reason for enhancement`: People who use Budgeteer responsibly to record earnings and costs may want to know about how to turn potential savings into stock investments. Rather than using a separate application to get stock prices and to calculate how much you can purchase, it's possible to access this information from the command line.
** `Highlights`: The implementation required extensive use of the cashflow implementation, and required parsing information from an external API. I had to read the documentation of the API to figure out how to retrieve the data and implement a useful scenario for it.
** `Credits`: The Alpha Vantage API was incorporated to implement this feature.

*_Major enhancements_* : Feature to return purchasing power and price of an entered cryptocurrency

** `Reason for enhancement`: People who use Budgeteer responsibly to record earnings and costs may want to know about how to turn potential savings into cryptocurrency investments. Rather than using a separate application to get cryptocurrency prices and to calculate how much you can purchase, it's possible to access this information from the command line.
** `Highlights`: The implementation required extensive use of the cashflow implementation, and required parsing information from an external API. I had to read the documentation of the API to figure out how to retrieve the data and implement a useful scenario for it.
** `Credits`: The Crypto Compare API was incorporated to implement this feature.

*_Major enhancements_* : Feature for price returns of bitcoin, ethereum, and litecoin

** `Credits`: The Crypto Compare API was incorporated to implement this feature.

=== *Other Contributions*

* *_Project management_* :
** Raised milestones and organized the group to complete each milestones before deadline.
** Ensured that milestone objectives were met and submitted to relevant PRs to module repo
** Support for issues tracker and PRs

* *_Documentation_* :
** Did cosmetic tweaks to existing contents of the User Guide and Developer Guide.
** Proof-read, organised documentation to maintain its coherence.

* *_Testing_*:
** Wrote tests to increase coverage of the project

* *_Tools_* :
** Incorporated the Alpha Vantage and Crypto Compare APIs into commands, and Reposense for contributions

* *_Team Management_* :
** Coordinated some team meetings

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the <<../UserGuide, User Guide>>. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=bitcoin]

include::../UserGuide.adoc[tag=ethereum]

include::../UserGuide.adoc[tag=litecoin]

include::../UserGuide.adoc[tag=stock]

include::../UserGuide.adoc[tag=crypto]

include::../UserGuide.adoc[tag=invest]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=crypto]
